/**
 * Data loading utilities for CalChildWatch
 * Handles loading facility data from JSON files generated by the scraper
 */

// California counties with metadata
export const CALIFORNIA_COUNTIES = [
  { name: "Alameda", population: 1682353, region: "Bay Area" },
  { name: "Alpine", population: 1204, region: "Sierra Nevada" },
  { name: "Amador", population: 40474, region: "Central Sierra" },
  { name: "Butte", population: 211632, region: "North Valley" },
  { name: "Calaveras", population: 45292, region: "Central Sierra" },
  { name: "Colusa", population: 21917, region: "North Valley" },
  { name: "Contra Costa", population: 1165927, region: "Bay Area" },
  { name: "Del Norte", population: 27743, region: "North Coast" },
  { name: "El Dorado", population: 193221, region: "Central Sierra" },
  { name: "Fresno", population: 1008654, region: "Central Valley" },
  { name: "Glenn", population: 28917, region: "North Valley" },
  { name: "Humboldt", population: 136310, region: "North Coast" },
  { name: "Imperial", population: 179702, region: "Southern Border" },
  { name: "Inyo", population: 19016, region: "Eastern Sierra" },
  { name: "Kern", population: 909235, region: "Central Valley" },
  { name: "Kings", population: 153443, region: "Central Valley" },
  { name: "Lake", population: 68163, region: "North Coast" },
  { name: "Lassen", population: 32730, region: "Northeast" },
  { name: "Los Angeles", population: 9829544, region: "Southern California" },
  { name: "Madera", population: 160089, region: "Central Valley" },
  { name: "Marin", population: 262321, region: "Bay Area" },
  { name: "Mariposa", population: 17131, region: "Central Sierra" },
  { name: "Mendocino", population: 91305, region: "North Coast" },
  { name: "Merced", population: 286461, region: "Central Valley" },
  { name: "Modoc", population: 8700, region: "Northeast" },
  { name: "Mono", population: 13195, region: "Eastern Sierra" },
  { name: "Monterey", population: 439035, region: "Central Coast" },
  { name: "Napa", population: 138019, region: "Bay Area" },
  { name: "Nevada", population: 102241, region: "Central Sierra" },
  { name: "Orange", population: 3186989, region: "Southern California" },
  { name: "Placer", population: 412300, region: "Central Sierra" },
  { name: "Plumas", population: 19790, region: "Northeast" },
  { name: "Riverside", population: 2458395, region: "Southern California" },
  { name: "Sacramento", population: 1585055, region: "Capital Region" },
  { name: "San Benito", population: 66677, region: "Central Coast" },
  { name: "San Bernardino", population: 2194710, region: "Southern California" },
  { name: "San Diego", population: 3298634, region: "Southern Border" },
  { name: "San Francisco", population: 873965, region: "Bay Area" },
  { name: "San Joaquin", population: 789410, region: "Central Valley" },
  { name: "San Luis Obispo", population: 283111, region: "Central Coast" },
  { name: "San Mateo", population: 764442, region: "Bay Area" },
  { name: "Santa Barbara", population: 446527, region: "Central Coast" },
  { name: "Santa Clara", population: 1936259, region: "Bay Area" },
  { name: "Santa Cruz", population: 267792, region: "Central Coast" },
  { name: "Shasta", population: 182155, region: "North Valley" },
  { name: "Sierra", population: 3236, region: "Northeast" },
  { name: "Siskiyou", population: 44076, region: "Northeast" },
  { name: "Solano", population: 453491, region: "Bay Area" },
  { name: "Sonoma", population: 488863, region: "Bay Area" },
  { name: "Stanislaus", population: 552999, region: "Central Valley" },
  { name: "Sutter", population: 99063, region: "North Valley" },
  { name: "Tehama", population: 65829, region: "North Valley" },
  { name: "Trinity", population: 16060, region: "North Coast" },
  { name: "Tulare", population: 477054, region: "Central Valley" },
  { name: "Tuolumne", population: 55620, region: "Central Sierra" },
  { name: "Ventura", population: 843843, region: "Southern California" },
  { name: "Yolo", population: 216403, region: "Capital Region" },
  { name: "Yuba", population: 81575, region: "North Valley" }
];

/**
 * Convert county name to filename format
 */
export const countyToFilename = (countyName) => {
  return countyName.toLowerCase().replace(/ /g, '_');
};

/**
 * Load facility data for a specific county
 * @param {string} countyName - Name of the county
 * @returns {Promise<Array>} Array of facility objects
 */
export const loadCountyData = async (countyName) => {
  try {
    const filename = countyToFilename(countyName);
    const response = await fetch(`/data/${filename}_facilities.json`);
    
    if (!response.ok) {
      console.warn(`No data file found for ${countyName}`);
      return null;
    }
    
    return await response.json();
  } catch (error) {
    console.error(`Error loading data for ${countyName}:`, error);
    return null;
  }
};

/**
 * Load summary data for all counties
 * @returns {Promise<Object>} Summary object
 */
export const loadSummary = async () => {
  try {
    const response = await fetch('/data/summary.json');
    
    if (!response.ok) {
      return null;
    }
    
    return await response.json();
  } catch (error) {
    console.error('Error loading summary:', error);
    return null;
  }
};

/**
 * Calculate statistics for a set of facilities
 * @param {Array} facilities - Array of facility objects
 * @returns {Object} Statistics object
 */
export const calculateStats = (facilities) => {
  if (!facilities || facilities.length === 0) {
    return {
      totalFacilities: 0,
      totalCapacity: 0,
      byType: {},
      byStatus: {},
      avgCapacity: 0,
      flaggedCount: 0
    };
  }

  const stats = {
    totalFacilities: facilities.length,
    totalCapacity: 0,
    byType: {},
    byStatus: {},
    avgCapacity: 0,
    flaggedCount: 0,
    withViolations: 0,
    recentlyInspected: 0
  };

  const now = new Date();
  const sixMonthsAgo = new Date(now.setMonth(now.getMonth() - 6));

  facilities.forEach(facility => {
    // Sum capacity
    stats.totalCapacity += facility.capacity || 0;

    // Count by type
    const type = facility.facility_type || 'Unknown';
    stats.byType[type] = (stats.byType[type] || 0) + 1;

    // Count by status
    const status = facility.status || 'Unknown';
    stats.byStatus[status] = (stats.byStatus[status] || 0) + 1;

    // Count facilities with violations
    if (facility.total_citations > 0) {
      stats.withViolations++;
    }

    // Count recently inspected
    if (facility.last_inspection_date) {
      const inspectionDate = new Date(facility.last_inspection_date);
      if (inspectionDate >= sixMonthsAgo) {
        stats.recentlyInspected++;
      }
    }

    // Check if flagged (based on various criteria)
    if (isFlagged(facility)) {
      stats.flaggedCount++;
    }
  });

  stats.avgCapacity = Math.round(stats.totalCapacity / stats.totalFacilities);

  return stats;
};

/**
 * Determine if a facility should be flagged for review
 * @param {Object} facility - Facility object
 * @returns {boolean} Whether facility is flagged
 */
export const isFlagged = (facility) => {
  const flags = getFlagReasons(facility);
  return flags.length > 0;
};

/**
 * Get reasons why a facility is flagged
 * @param {Object} facility - Facility object
 * @returns {Array<string>} Array of flag reasons
 */
export const getFlagReasons = (facility) => {
  const reasons = [];

  // High violation count
  if (facility.total_citations >= 5) {
    reasons.push(`High citation count: ${facility.total_citations}`);
  }

  // No recent inspection
  if (facility.last_inspection_date) {
    const lastInspection = new Date(facility.last_inspection_date);
    const sixMonthsAgo = new Date();
    sixMonthsAgo.setMonth(sixMonthsAgo.getMonth() - 6);
    
    if (lastInspection < sixMonthsAgo) {
      reasons.push('No inspection in 6+ months');
    }
  }

  // High capacity with limited inspection history
  if (facility.capacity > 50 && (!facility.total_visits || facility.total_visits < 2)) {
    reasons.push('High capacity facility with limited inspection history');
  }

  // Future: Add payment-based flags when subsidy data available
  // if (facility.subsidyPayments && facility.capacity) {
  //   const paymentPerSlot = facility.subsidyPayments / facility.capacity;
  //   if (paymentPerSlot > THRESHOLD) {
  //     reasons.push('Unusually high payment per capacity slot');
  //   }
  // }

  return reasons;
};

/**
 * Search facilities by name or address
 * @param {Array} facilities - Array of facility objects
 * @param {string} query - Search query
 * @returns {Array} Filtered facilities
 */
export const searchFacilities = (facilities, query) => {
  if (!query || query.trim() === '') {
    return facilities;
  }

  const lowerQuery = query.toLowerCase();
  
  return facilities.filter(facility => {
    return (
      (facility.name && facility.name.toLowerCase().includes(lowerQuery)) ||
      (facility.address && facility.address.toLowerCase().includes(lowerQuery)) ||
      (facility.city && facility.city.toLowerCase().includes(lowerQuery)) ||
      (facility.license_number && facility.license_number.includes(query))
    );
  });
};

/**
 * Filter facilities by various criteria
 * @param {Array} facilities - Array of facility objects
 * @param {Object} filters - Filter criteria
 * @returns {Array} Filtered facilities
 */
export const filterFacilities = (facilities, filters = {}) => {
  let filtered = [...facilities];

  if (filters.type) {
    filtered = filtered.filter(f => f.facility_type === filters.type);
  }

  if (filters.status) {
    filtered = filtered.filter(f => f.status === filters.status);
  }

  if (filters.flaggedOnly) {
    filtered = filtered.filter(f => isFlagged(f));
  }

  if (filters.minCapacity) {
    filtered = filtered.filter(f => f.capacity >= filters.minCapacity);
  }

  if (filters.maxCapacity) {
    filtered = filtered.filter(f => f.capacity <= filters.maxCapacity);
  }

  if (filters.hasViolations) {
    filtered = filtered.filter(f => f.total_citations > 0);
  }

  return filtered;
};

/**
 * Sort facilities by a given field
 * @param {Array} facilities - Array of facility objects
 * @param {string} field - Field to sort by
 * @param {string} direction - 'asc' or 'desc'
 * @returns {Array} Sorted facilities
 */
export const sortFacilities = (facilities, field = 'name', direction = 'asc') => {
  return [...facilities].sort((a, b) => {
    let aVal = a[field];
    let bVal = b[field];

    // Handle nulls
    if (aVal === null || aVal === undefined) aVal = '';
    if (bVal === null || bVal === undefined) bVal = '';

    // Numeric comparison for numbers
    if (typeof aVal === 'number' && typeof bVal === 'number') {
      return direction === 'asc' ? aVal - bVal : bVal - aVal;
    }

    // String comparison
    aVal = String(aVal).toLowerCase();
    bVal = String(bVal).toLowerCase();

    if (direction === 'asc') {
      return aVal.localeCompare(bVal);
    }
    return bVal.localeCompare(aVal);
  });
};

/**
 * Export facilities to CSV
 * @param {Array} facilities - Array of facility objects
 * @returns {string} CSV content
 */
export const exportToCSV = (facilities) => {
  const headers = [
    'License Number',
    'Name',
    'Type',
    'Address',
    'City',
    'Zip',
    'Capacity',
    'Status',
    'Last Inspection',
    'Citations',
    'CCLD URL'
  ];

  const rows = facilities.map(f => [
    f.license_number,
    `"${(f.name || '').replace(/"/g, '""')}"`,
    f.facility_type,
    `"${(f.address || '').replace(/"/g, '""')}"`,
    f.city,
    f.zip_code,
    f.capacity,
    f.status,
    f.last_inspection_date || '',
    f.total_citations || 0,
    f.ccld_url
  ]);

  return [headers.join(','), ...rows.map(r => r.join(','))].join('\n');
};

export default {
  CALIFORNIA_COUNTIES,
  countyToFilename,
  loadCountyData,
  loadSummary,
  calculateStats,
  isFlagged,
  getFlagReasons,
  searchFacilities,
  filterFacilities,
  sortFacilities,
  exportToCSV
};
