/**
 * Minnesota counties with population and region data
 * 87 counties total
 */
export const MINNESOTA_COUNTIES = [
  { name: "Aitkin", population: 15886, region: "Central" },
  { name: "Anoka", population: 363887, region: "Twin Cities Metro" },
  { name: "Becker", population: 34767, region: "West Central" },
  { name: "Beltrami", population: 47188, region: "Northwest" },
  { name: "Benton", population: 41379, region: "Central" },
  { name: "Big Stone", population: 4991, region: "West Central" },
  { name: "Blue Earth", population: 67653, region: "South Central" },
  { name: "Brown", population: 25008, region: "South Central" },
  { name: "Carlton", population: 35871, region: "Northeast" },
  { name: "Carver", population: 106922, region: "Twin Cities Metro" },
  { name: "Cass", population: 29779, region: "Central" },
  { name: "Chippewa", population: 11800, region: "West Central" },
  { name: "Chisago", population: 56543, region: "Twin Cities Metro" },
  { name: "Clay", population: 64222, region: "West Central" },
  { name: "Clearwater", population: 8818, region: "Northwest" },
  { name: "Cook", population: 5463, region: "Northeast" },
  { name: "Cottonwood", population: 11196, region: "Southwest" },
  { name: "Crow Wing", population: 65055, region: "Central" },
  { name: "Dakota", population: 439882, region: "Twin Cities Metro" },
  { name: "Dodge", population: 20867, region: "Southeast" },
  { name: "Douglas", population: 38141, region: "West Central" },
  { name: "Faribault", population: 13653, region: "South Central" },
  { name: "Fillmore", population: 21067, region: "Southeast" },
  { name: "Freeborn", population: 29895, region: "South Central" },
  { name: "Goodhue", population: 46340, region: "Southeast" },
  { name: "Grant", population: 5868, region: "West Central" },
  { name: "Hennepin", population: 1281565, region: "Twin Cities Metro" },
  { name: "Houston", population: 18600, region: "Southeast" },
  { name: "Hubbard", population: 21491, region: "Central" },
  { name: "Isanti", population: 41000, region: "Twin Cities Metro" },
  { name: "Itasca", population: 45130, region: "Northeast" },
  { name: "Jackson", population: 9846, region: "Southwest" },
  { name: "Kanabec", population: 16337, region: "Central" },
  { name: "Kandiyohi", population: 43495, region: "West Central" },
  { name: "Kittson", population: 4208, region: "Northwest" },
  { name: "Koochiching", population: 12229, region: "Northeast" },
  { name: "Lac qui Parle", population: 6623, region: "West Central" },
  { name: "Lake", population: 10651, region: "Northeast" },
  { name: "Lake of the Woods", population: 3719, region: "Northwest" },
  { name: "Le Sueur", population: 28887, region: "South Central" },
  { name: "Lincoln", population: 5639, region: "Southwest" },
  { name: "Lyon", population: 25474, region: "Southwest" },
  { name: "Mahnomen", population: 5527, region: "Northwest" },
  { name: "Marshall", population: 9039, region: "Northwest" },
  { name: "Martin", population: 19683, region: "South Central" },
  { name: "McLeod", population: 35893, region: "South Central" },
  { name: "Meeker", population: 23149, region: "Central" },
  { name: "Mille Lacs", population: 26277, region: "Central" },
  { name: "Morrison", population: 33386, region: "Central" },
  { name: "Mower", population: 40062, region: "Southeast" },
  { name: "Murray", population: 8194, region: "Southwest" },
  { name: "Nicollet", population: 34274, region: "South Central" },
  { name: "Nobles", population: 21629, region: "Southwest" },
  { name: "Norman", population: 6375, region: "Northwest" },
  { name: "Olmsted", population: 162847, region: "Southeast" },
  { name: "Otter Tail", population: 59029, region: "West Central" },
  { name: "Pennington", population: 14349, region: "Northwest" },
  { name: "Pine", population: 29579, region: "Central" },
  { name: "Pipestone", population: 9126, region: "Southwest" },
  { name: "Polk", population: 31364, region: "Northwest" },
  { name: "Pope", population: 11249, region: "West Central" },
  { name: "Ramsey", population: 552352, region: "Twin Cities Metro" },
  { name: "Red Lake", population: 3896, region: "Northwest" },
  { name: "Redwood", population: 15170, region: "Southwest" },
  { name: "Renville", population: 14548, region: "South Central" },
  { name: "Rice", population: 66972, region: "South Central" },
  { name: "Rock", population: 9315, region: "Southwest" },
  { name: "Roseau", population: 15165, region: "Northwest" },
  { name: "Scott", population: 150928, region: "Twin Cities Metro" },
  { name: "Sherburne", population: 97238, region: "Twin Cities Metro" },
  { name: "Sibley", population: 14865, region: "South Central" },
  { name: "St. Louis", population: 200231, region: "Northeast" },
  { name: "Stearns", population: 161075, region: "Central" },
  { name: "Steele", population: 36649, region: "South Central" },
  { name: "Stevens", population: 9805, region: "West Central" },
  { name: "Swift", population: 9266, region: "West Central" },
  { name: "Todd", population: 24664, region: "Central" },
  { name: "Traverse", population: 3259, region: "West Central" },
  { name: "Wabasha", population: 21627, region: "Southeast" },
  { name: "Wadena", population: 13682, region: "Central" },
  { name: "Waseca", population: 18612, region: "South Central" },
  { name: "Washington", population: 267568, region: "Twin Cities Metro" },
  { name: "Watonwan", population: 10695, region: "South Central" },
  { name: "Wilkin", population: 6207, region: "West Central" },
  { name: "Winona", population: 50847, region: "Southeast" },
  { name: "Wright", population: 141337, region: "Twin Cities Metro" },
  { name: "Yellow Medicine", population: 9709, region: "Southwest" }
];

export default MINNESOTA_COUNTIES;
